# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -s h -l help -d 'Prints help information'
complete -c alacritty -l hold -d 'Remain open after child process exits'
complete -c alacritty -l print-events -d 'Print all events to stdout'
complete -c alacritty -s q -d 'Reduces the level of verbosity (the min level is -qq)'
complete -c alacritty -l ref-test -d 'Generates ref test'
complete -c alacritty -s v -d 'Increases the level of verbosity (the max level is -vvv)'
complete -c alacritty -s V -l version -d 'Prints version information OPTIONS'
complete -c alacritty -l working-directory -d 'Start the shell in the specified working directory SUBCOMMANDS'

