# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#151515'
    background: '#151515'
    # soft contrast: background = '#251b1d'
    foreground: '#ffffff'

  # Normal colors
  normal:
    black:   '#000000'
    red:     '#db4b33'
    green:   '#9ec825'
    yellow:  '#ffff00' 
    # yellow:  '#e6e200'
    blue:    '#0091ff'
    magenta: '#4d459b'
    cyan:    '#30d5c8'
    white:   '#bfc1c2'

  # Bright colors
  bright:
    black:   '#251b1d'
    red:     '#f77a6a'
    green:   '#bdff00'
    yellow:  '#fbec5d'
    blue:    '#3ebbdb'
    magenta: '#9991e3'
    cyan:    '#00ffff'
    white:   '#ffffff'
