[colors.bright]
black = "#cd764d"
blue = "#0091ff"
cyan = "#00ffff"
green = "#bdff00"
magenta = "#9991e3"
red = "#f77a6a"
white = "#ffffff"
yellow = "#ffff00"

[colors.normal]
black = "#3c1f11"
blue = "#0f71ff"
cyan = "#00c3cf"
green = "#9ec825"
magenta = "#6d67af"
red = "#db4b33"
white = "#bfc1c2"
yellow = "#fbec5d"

[colors.primary]
background = "#151515"
foreground = "#ffffff"
