#! /bin/bash
#------------------------------------------------------------------
#- Script by: mxzcabel
#- https://github.com/mxzcabel
#- Date: 24/08/03
#- https://wiki.hyprland.org/IPC/#xdg_runtime_dirhyprhissocketsock
#- Description: This script activate other keymaps for specific
#-------------- applications and trigger back to the original if
#-------------- any other 'activewindow' event is detected.
#-------------- in this example Emacs is the triggered application.
#------------------------------------------------------------------
#
#---------/---------/------------/--------------/------------------
# Keyboard device name
myKeyboards=("g915-keyboard-keyboard" "logitech-usb-receiver-keyboard" "logitech-g915-wireless-rgb-mechanical-gaming-keyboard")
# The application you desire to switch keymaps
application="[Ee]\macs"
# The language keyboard will set back
language="English"
#---------/---------/------------/--------------/------------------
# Detect if the specific keyboard is available
function getKeyboard () {
  printf '%s' "$(hyprctl devices | sed -En 's/('$1')$/\1/p')"
}
#---------/---------/------------/--------------/------------------
# Change keyboard if a match is detected
function changeKeyboard () {
  for keyboard in "${myKeyboards[@]}"
  do
    if [[ -n $(getKeyboard "$keyboard") ]]; then
      keymap=$(printf '%s' "$keyboard")
      return 0
    fi
  done
  return 1
}
#---------/---------/------------/--------------/------------------
# Get the match language to set back keymap layout
function getKeymap () {
  printf '%s' "$(printf '%s' $(hyprctl devices -j | awk 'c&&c!--c;/"'$1'"/{c=6}' | sed -n 's/"active_keymap": *.\('$language'\).*/\1/p'))"
}
#---------/---------/------------/--------------/------------------
# Get desired application within socket2
function detectedApp () {
  printf '%s' "$(printf '%s' $1 | sed -n "s/\(activewindow>>$application,\)/\1/p" | sed -n 's/^.*\('"$application"',\).*/\1/g p')"
}
#---------/---------/------------/--------------/------------------
# Get any other window name within socket2
function anyOtherWindow () {
  printf '%s' "$(printf '%s' $1 | sed -n "s/\(activewindow>>\)/\1/p" | sed -e 's/^.*'"$application"',.*//g')"
}
#---------/---------/------------/--------------/------------------
# Handle the process to set the desire keymap for chosen keyboard
function handle () {
  ## Switch to second keymap if application is an activewindow
  if [[ -n $(detectedApp "$1") ]]; then
      if changeKeyboard; then
          if [[ $(getKeymap "$keymap") == $language ]]; then
            hyprctl switchxkblayout $keymap 1 >/dev/null
          fi
      fi
  fi
  ## Switch to the main keymap if any other application is an activewindow
  if [[ -z $(detectedApp "$1") ]] && [[ -n $(anyOtherWindow "$1") ]]; then
      if changeKeyboard; then
          if [[ $(getKeymap "$keymap") != $language ]]; then
            hyprctl switchxkblayout $keymap 0 >/dev/null
          fi
      fi
  fi
}
#---------/---------/------------/--------------/------------------
# Hyprland socket2
socat -U - UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock | while read -r line; do handle "$line"; done
